[settings]
network_type = "testnet"
log_level = "debug"
host = "0.0.0.0"
port = 8081
coin_market_cap_api_key = "01016cb4-f4a1-493f-a398-d7990f964029"
sqlite_db_path = "db.sqlite"
api_version = { 0 = "v1", 1 = "v2" }

[accounts.0]
chain_id = 97
available = true
# Unique in the accounts list
private_key = "eac14b2f62136a72601430dfb9abce2f4b98dabef428f5f92869ef85997e8f84"
# If supported_erc20_list is empty, all erc20 tokens will not be supported
supported_erc20_tokens = { 0 = "mtt", 1 = "musd" }
balance_alarm_threshold = 0.05
balance_check_interval_ms = 500000

[accounts.1]
chain_id = 5
available = true
# Unique in the accounts list
private_key = "eac14b2f62136a72601430dfb9abce2f4b98dabef428f5f92869ef85997e8f84"
# If supported_erc20_list is empty, all erc20 tokens will not be supported
supported_erc20_tokens = { 0 = "mtt", 1 = "musd" }
balance_alarm_threshold = 1
balance_check_interval_ms = 500000
